services:
  yt-plex:
    image: yt-plex:latest
    restart: unless-stopped
    environment:
      - XDG_DATA_HOME=/data
    ports:
      - "32113:3000"
    volumes:
      - /docker/yt-plex/config:/config   # config.toml
      - /docker/yt-plex/data:/data       # SQLite DB + thumbnail cache
      - /mnt/media2:/media               # Plex media directory
